### ISSUE TITLE
ordered list are cut

### ISSUE THREAD

**Issue by eephyne** [ppoffice/hexo-theme-hueman#10]
It seem (I didn't test a lot) that ordered list are a bit hidden in the left)

![](http://i.imgur.com/E0WXmKV.png)
(the two at the end are two digit numbers

**Comment by eephyne** [comment]
better but still not solved

![](http://i.imgur.com/sdMqtb6.png)

**Comment by ppoffice** [comment]
try this out

**Comment by eephyne** [comment]
work perfectly here (tested with 4-digit ordered list).

thanks as always :)
