### ISSUE TITLE
关于子菜单

### ISSUE THREAD

**Issue by luoshuai123** [ppoffice/hexo-theme-hueman#100]
这是官方关于子菜单的例子：
![2016-03-12 16 40 03 -1](https://cloud.githubusercontent.com/assets/14179498/13722535/02c1cf4a-e884-11e5-9063-388ebf288bec.png)

然后我的config.yml配置文件如下：

![2016-03-12 18 56 30 -1](https://cloud.githubusercontent.com/assets/14179498/13722560/a29a2e90-e884-11e5-9594-2925338c87bf.png)

为何hexo g的时候是报错，然而吧categories下面的两行删掉又能generate成功！
githubde的编辑器不太会用，见笑了

**Comment by ppoffice** [comment]
看不懂你的问题，请注意排版。
另外_config.yml中的categroies后面不能跟任何值。

**Comment by luoshuai123** [comment]
经过实际操作，我已经里理解官网这一段话的内容了。打扰了
