### ISSUE TITLE
search option: hexo-generator-search

### ISSUE THREAD

**Issue by veramartins** [ppoffice/hexo-theme-hueman#102]
Baidu is not recomended, Swiftkey no longer has a free service and Google has it's own issues.
So, I'm asking for hueman to support hexo-generator-search. It is beautiful and fast. I tried hacking away, but I'm not proficient enough yet to make it work. Here is a guide that does work in case you are interested:
[google cached version](http://webcache.googleusercontent.com/search?q=cache:66niEqBKp5sJ:www.junonguyen.com/2016/01/22/How-to-create-Local-Search-Engine-for-your-blog-with-hexo-generate-search-plugin/+&cd=1&hl=en&ct=clnk&gl=pt)

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
Thank you for advise. I will look into this soon.

**Comment by veramartins** [comment]
Thanks. It will mean a lot to newbies like me.

**Comment by ppoffice** [comment]
@veramartins 

Sorry for this late update, I added a new local search engine named Insight, hope you will like it.

To try it out, please install `hexo-generator-json-content`, and also pull the latest version of this theme. Finally don't forget to add the following line to your _config.yml:

```diff
# Search
search:
+   insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false
```

PS:
[Online Preview](http://blog.zhangruipeng.me/hexo-theme-hueman/#ins-search)

**Comment by veramartins** [comment]
Thanks, it looks great! I'll install it over the weekend.
With this local search option, Hueman made Hexo work perfectly for me, and I suspect for many others to come. I know all of this existed here and there, but the way Hueman integrates it makes it an option for real sites with lots of content.
