### ISSUE TITLE
建议支持“畅言”

### ISSUE THREAD

**Issue by zxz054321** [ppoffice/hexo-theme-hueman#103]
在国内 畅言 还是挺好用的

**Comment by cow5910878** [comment]
这个可以增加多说吗？

**Comment by ppoffice** [comment]
@cow5910878 
已经支持多说了
https://github.com/ppoffice/hexo-theme-hueman/wiki/Comment#duoshuo

**Comment by tinyvane** [comment]
我自己修改了代码，已经可以支持暢言，但是我想请问楼主，那个阅读量是如何获取到的？我没有发现有相关的js负责更新每个页面角落上的阅读量，请问是怎么做到的？我在hexo中也没有发现相关的js

**Comment by ppoffice** [comment]
@tinyvane 本主题没有阅读量插件

**Comment by tinyvane** [comment]
@ppoffice 抱歉，笔误，是评论量

**Comment by ppoffice** [comment]
@tinyvane 其他评论插件的实现代码在这里：https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/comment/counter.ejs
如果你使用的评论插件本身没有评论量接口的话就没法实现了。

**Comment by tinyvane** [comment]
@ppoffice 谢谢回复，暢言是有接口的。这个文件我找到了，暢言提供了一个js来获取，请问这个文件我有点看不懂呢，如何调用暢言提供的js文件呢？

**Comment by tinyvane** [comment]
@ppoffice <span id="sourceId::{your changeyan sourceid}" class="cy_cmt_count"></span>
        <script id="cy_cmt_num" src="http://changyan.sohu.com/upload/plugins/plugins.list.count.js?clientId=cysTFexTx">
</script>这是暢言官方提供的方法，这句话应该加到哪个文件里呢？如果是放在counter.ejs里面的话，列表页会加载多次

**Comment by ppoffice** [comment]
@tinyvane 
请尝试这里：https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/common/scripts.ejs
