### ISSUE TITLE
loading spinner never goes away

### ISSUE THREAD

**Issue by darwinairola** [ppoffice/hexo-theme-hueman#104]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

I have set the src field of one of my images dynamically, and the Fancybox loading spinner never goes away on a mobile platform. I have tried many things to get rid of the spinner on that image, but nothing seems to work. Is there a way to disable Fancybox, altogether?

Okay, I (finally) managed to get the loading spinner to go away by disabling scrollLoading. Ugh. If you ever fix this, please let me know.

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-hueman/blob/master/_config.yml.example#L54

Try to set
```
scrollLoading: false
```

**Comment by darwinairola** [comment]
Thanks, yes; that made the issue go away.
