### ISSUE TITLE
When I update to hexo 3.2, there is an error Process Failed

### ISSUE THREAD

**Issue by tim-hub** [ppoffice/hexo-theme-hueman#106]
> ERROR Process failed: layout/_partial/after-footer.ejs

And a lot other ejs files

**Comment by ppoffice** [comment]
Please follow the instructions and try to reinstall the theme.
https://github.com/ppoffice/hexo-theme-hueman/wiki

**Comment by tim-hub** [comment]
still an error after I init a new site and re install the theme.

Unhandled rejection TypeError:

**Comment by ppoffice** [comment]
Did you rename `_config.yml.example` file?

**Comment by tim-hub** [comment]
No. You are right, I found it. Thanks.
