### ISSUE TITLE
为什么我的网站手机上适配不正常

### ISSUE THREAD

**Issue by bikegl** [ppoffice/hexo-theme-hueman#107]
你的站点是可以自动适配的:
http://7xsfpm.com1.z0.glb.clouddn.com/you-friendly.png
但是我的却不行:
http://7xsfpm.com1.z0.glb.clouddn.com/me-no-friendly.png
难道是我漏掉了什么配制?

**Comment by ppoffice** [comment]
我这儿用手机看正常呀
你是用什么网站测试的？

**Comment by bikegl** [comment]
使用微软必应测试:
https://www.bing.com/webmaster/tools/mobile-friendliness

** 有一种情况我的网站是可以适配的:
先访问你的网站后,接着访问我的网站当时可以正常适配,如果单独访问就不能适配

**Comment by ppoffice** [comment]
为啥你的网站被套了Frame？
![image](https://cloud.githubusercontent.com/assets/8849362/15090361/7a713ecc-1458-11e6-88a3-fde9297e89e7.png)

**Comment by bikegl** [comment]
多谢提醒, 可能是域名搞的
