### ISSUE TITLE
文章中的图片和缩略图不能加载

### ISSUE THREAD

**Issue by JayceCao** [ppoffice/hexo-theme-hueman#111]
文章的开头使用绝对路径引入了一张图片，在编辑器预览窗口中的显示是正确的，但是在浏览器中不能正确加载，缩略图也没有显示，这是为什么呢。。还有favicon图片也不能正常加载，是不是对favicon图片尺寸有要求？

**Comment by ppoffice** [comment]
能给一下地址么？或者贴一下代码或者错误信息？

**Comment by JayceCao** [comment]
@ppoffice  JayceCao.github.io

**Comment by ppoffice** [comment]
你的图片是放在那个文件夹下面的？

**Comment by JayceCao** [comment]
@ppoffice  放在了’/images/‘下面呢

**Comment by ppoffice** [comment]
是`/source/images`下面还是直接放到了`/images`下面

**Comment by JayceCao** [comment]
直接放到了/imgages/下面

**Comment by ppoffice** [comment]
你放到`/source/images`再部署到线上试一下

**Comment by JayceCao** [comment]
@ppoffice  解决了！多谢帮助！感谢！
