### ISSUE TITLE
主页的灰色背景能替换成自定义图片吗

### ISSUE THREAD

**Issue by JayceCao** [ppoffice/hexo-theme-hueman#113]
主页的前半部分是灰色背景，能不能用图片替换掉呢

**Comment by ppoffice** [comment]
修改这里：https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_partial/header.styl#L2

**Comment by JayceCao** [comment]
@ppoffice 应该怎样修改啊。。。

**Comment by edwardkuo** [comment]
可以這樣修改  background-image: url("/img/head.jpg")
