### ISSUE TITLE
Feature request : Google Analytics

### ISSUE THREAD

**Issue by shark-oxi** [ppoffice/hexo-theme-hueman#116]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully;
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

Hi,

Is it possible to implement a Google Analytics feature in your theme ?

For example the default [light theme](https://github.com/hexojs/hexo-theme-light) have a simple google analytics line in his `_config.yml` config file.

I don't think it's very complicated as you have just to add a short script at the right place.

Keep me tuned :)

**Comment by ppoffice** [comment]
Do you mean this? https://github.com/ppoffice/hexo-theme-hueman/wiki/Plugins#google-analytics

**Comment by shark-oxi** [comment]
I think I didn't read the theme wiki so carefully in fact ... sorry

I think I'm blind ...
