### ISSUE TITLE
关于在md中插入音乐

### ISSUE THREAD

**Issue by mBigFlower** [ppoffice/hexo-theme-hueman#117]
你好。
   我看了原版的hueman，简直不要太炫酷。
   这里想问下，像原版的那种，插入音乐后，在thumbnail图片上有个小按钮，并且点进文章后，能像原版那种，在md中能操作实现吗？如果可以，要怎么做？
![image](https://cloud.githubusercontent.com/assets/11960705/15745434/6544aa50-2904-11e6-827c-083e000bf4f6.png)

**Comment by ppoffice** [comment]
@mBigFlower 
原版Markdown中好像没有插入视频和音频的语法……所以如果真的需要用thumbnail显示音乐或者视频可能就需要使用Hexo的API来实现了。
