### ISSUE TITLE
Impossible to set categories menu

### ISSUE THREAD

**Issue by eduardolagunas** [ppoffice/hexo-theme-hueman#119]
Hi,

I'm trying to set categories menu like in image, but I don´t get any result.

![issue](https://cloud.githubusercontent.com/assets/15438307/15776449/d5de9b6c-2987-11e6-98ac-4801d87edf7c.PNG)

what's wrong with this?

- [X] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully;
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
You should leave `Categories` field empty and set the category of each post according to https://hexo.io/docs/front-matter.html

**Comment by eduardolagunas** [comment]
Hi,

I understood the categories wrongly.

Thanks, I close this.
