### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by dowhilenet** [ppoffice/hexo-theme-hueman#12]
非常喜欢你的theme。在本地执行`hexo s`都可以看到完整的theme ，可是` hexo d `之后访问却没有css样式。<http://dowhile.net/blog>

**Comment by ppoffice** [comment]
你用的是哪个版本的hexo？可能需要重新安装`hexo-renderer-stylus`
参考https://github.com/hexojs/hexo/issues?q=stylus

**Comment by dowhilenet** [comment]
谢谢你，我找到了我对应的问题。
