### ISSUE TITLE
Theme not rendering properly

### ISSUE THREAD

**Issue by ishu3101** [ppoffice/hexo-theme-hueman#129]
After installing the hueman theme, when I preview it this is what I see.

I'm using `node js: v0.10.35, hexo: 3.2.2, hexo-cli: 1.0.2`

I'm getting two different results when I run it.

When I ran it the first time, this is what I saw.

![](http://i.imgur.com/a3cwHuV.png)

But now when I preview it again, I'm getting this.

![](http://i.imgur.com/X4OSIwC.png)

**Comment by ppoffice** [comment]
@ishu3101 
Please post your configuration file or log from Hexo console.

**Comment by ishu3101** [comment]
Where do you find the log? The only changes that I have made to the `_config.yml` file from the default installing of Hexo is the theme.

**Comment by ppoffice** [comment]
@ishu3101 
Please follow this [guide](https://github.com/ppoffice/hexo-theme-hueman/wiki/Installation) and reinstall the theme, and show me the output of your Shell/CMD in which you run the `hexo-cli` when you encounter an error.

**Comment by ishu3101** [comment]
After reinstalling the theme, I still see the same results. No error is shown in the console when I run the command `hexo server` in the root of my blog directory.

**Comment by ppoffice** [comment]
@ishu3101 
Would you please give me your blog's link or source code? I can hardly tell anything from your screenshots.

**Comment by ishu3101** [comment]
I have not deployed my blog yet? I have just installed hexo and created a blog with all the default settings with the only change being the theme.

**Comment by ppoffice** [comment]
have you rename the _config.yml.example file under the theme folder?

**Comment by ishu3101** [comment]
Yes

**Comment by ppoffice** [comment]
@ishu3101 
I tested [the example site](https://github.com/ppoffice/hexo-theme-hueman/tree/site) inside a Docker under `node js: v0.10.35, hexo: 3.2.2, hexo-cli: 1.0.2`, and everything works perfectly. Please clone [the example site](https://github.com/ppoffice/hexo-theme-hueman/tree/site) and test it yourself, and let me know if anything goes wrong.
