### ISSUE TITLE
Responsive layout not working on mobile

### ISSUE THREAD

**Issue by JasonKing66** [ppoffice/hexo-theme-hueman#132]
jwang138.com

I locally test different device resolutions through Chrome developer tool and `hexo serve`. The responsive layout always works.
But after I deploy it, the responsive is missing. I always have default layout, not mobile optimized.

**Comment by ppoffice** [comment]
Your site was framed.
![image](https://cloud.githubusercontent.com/assets/8849362/17461979/179cb158-5cd0-11e6-9e17-7e76dc35c18c.png)
#107

**Comment by JasonKing66** [comment]
Okay I just found out it's caused by my domain settings. I enabled "forward with musk" feature in Godaddy. That's where I added extra layer and frame. Thanks for pointing out.
