### ISSUE TITLE
Support for photo galleries

### ISSUE THREAD

**Issue by dupersuper** [ppoffice/hexo-theme-hueman#134]
Hello there, this is more of a question than an issue.

I wasn't able to find in your doc something about photo galleries. Does your theme supports photo galleries?

Thank you

**Comment by ppoffice** [comment]
I just add the gallery feature to this theme. Please go to [this page](http://blog.zhangruipeng.me/hexo-theme-hueman/2015/01/26/Gallery-Example/) to preview. And please be reminded that the configuration file and the documentation are updated to.

**Comment by dupersuper** [comment]
Looks amazing! Going to try that! Thank you!
