### ISSUE TITLE
首页可以产生图片,可是其他页面的图片没有产生

### ISSUE THREAD

**Issue by TingSyuanWang** [ppoffice/hexo-theme-hueman#138]
麻烦大大参考一下网站：

首页：https://tingsyuanwang.github.io/blogs/
分类：https://tingsyuanwang.github.io/blogs/categories/%E6%8A%80%E8%A1%93%E5%88%86%E4%BA%AB/

辛苦了

**Comment by ppoffice** [comment]
@TingSyuanWang 
因为你这个是二级目录的博客，所以图片请使用绝对地址（/blogs/images/hellojs.jpg）
或者将网站的_config.yml中的`url`去掉/blogs/部分

**Comment by TingSyuanWang** [comment]
太棒了，顺利成功，谢谢
