### ISSUE TITLE
Supporting submenus

### ISSUE THREAD

**Issue by lebarde** [ppoffice/hexo-theme-hueman#139]
Hello,
Would it be possible to support submenus like this for instance:

```
menu:
    Home: /
    Exercices: /exercices/
    Categories:
    Prices and Contact: /tarifs-contact/
```

Thanks a lot! Your theme is nice!

**Comment by ppoffice** [comment]
@lebarde 
It should show custom menus. But you need to add their translations in the language files.

**Comment by D-Rusty** [comment]
您好在_confiy.yml 中添加了该段代码:
  menu:
    Home: /
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /
   +  Github: https://github.com/D-Rusty
为什么会显示成：index.github?
![image](https://cloud.githubusercontent.com/assets/17473495/18344692/e4081858-75ea-11e6-94e2-d2d528f3ff90.png)
可以提供详细的关于hueman的配置文档吗？谢谢

**Comment by ppoffice** [comment]
@D-Rusty 
在[这个文件](https://github.com/ppoffice/hexo-theme-hueman/blob/master/languages/zh-CN.yml)的`index`下面加上：
```diff
index:
    home: '主页'
    about: '关于'
    search: '搜索'
    archive: '归档'
    category: '分类：'
    uncategorized: '未分类'
    tag: '标签：'
+   github: 'GitHub'
```

**Comment by lebarde** [comment]
Sorry but i only speak english and french.

**Comment by ppoffice** [comment]
@lebarde 
I updated comments.:smile:

**Comment by lebarde** [comment]
Thanks :)
