### ISSUE TITLE
最上方能设置背景图片吗？

### ISSUE THREAD

**Issue by clayclayclay** [ppoffice/hexo-theme-hueman#145]
![image](https://cloud.githubusercontent.com/assets/13716195/18999807/02e79030-8772-11e6-83a4-eaccc12f6187.png)
我想问这个黑色背景能换成图片吗？能的话，配置哪个属性？在哪里？

**Comment by clayclayclay** [comment]
还有，能有自定义的头像吗？除了那个logo图案

**Comment by ppoffice** [comment]
#113
