### ISSUE TITLE
Support mathjax?

### ISSUE THREAD

**Issue by searene** [ppoffice/hexo-theme-hueman#146]
Is there any plan to support mathjax?

**Comment by ppoffice** [comment]
@searene 
Sorry, but not yet.

**Comment by ppoffice** [comment]
MathJax support added. Please refer to [this example](http://blog.zhangruipeng.me/hexo-theme-hueman/2016/07/08/MathJax-Example/) 😄

**Comment by searene** [comment]
@ppoffice This is really amazing, thank you for your hard work!
