### ISSUE TITLE
Do you also create Hexo themes of other themes (private job?)

### ISSUE THREAD

**Issue by Salexes** [ppoffice/hexo-theme-hueman#150]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

I could not find where to contact you which is why I write here, please answer here or send me your contact details (I am new to GitHub, sorry if this is the wrong way to contact somebody)

**Comment by ppoffice** [comment]
@Salexes 
I'm busy with some tricky private projects recently, so I'm afraid that I don't have enough time for the next few months to participate in any other projects:cry:.

**Comment by Salexes** [comment]
Oh sad to hear that. Hope your projects will be successful.

Do you have recommendations where I could fined someone to convert my WP Theme to Hexo ?

**Comment by ppoffice** [comment]
@Salexes 
Maybe you can ask other Hexo theme developer to check if they are available.
