### ISSUE TITLE
在本地端开启没有问题,但是放到gh-pages就出现问题了

### ISSUE THREAD

**Issue by TingSyuanWang** [ppoffice/hexo-theme-hueman#151]
###以前不会，不知道什么时候出现问题的。

![2016-11-03 3 05 19](https://cloud.githubusercontent.com/assets/8935531/19958097/35487f2e-a1d7-11e6-8158-ad284eac0c4a.png)

**Comment by ppoffice** [comment]
@TingSyuanWang 
请尝试删除gh-pages后重新Deploy到GitHub，可能是上次部署的时候文件上传不完全造成的。

**Comment by TingSyuanWang** [comment]
@ppoffice 是把整個branch刪除嗎?

**Comment by TingSyuanWang** [comment]
@ppoffice 是把整个branch删除吗?

**Comment by TingSyuanWang** [comment]
@ppoffice 重新部署过了，删掉branch也不行〜
再拜托您看看了！

**Comment by TingSyuanWang** [comment]
有可能跟node或是hexo版本有关系吗？

**Comment by zippoobbiz** [comment]
需要添加一个.noJekyll文件在你repository的根目录下
可以参考http://philsblog.info/2016/09/04/Github-Pages-cannot-get-access-to-vendor-folder-when-using-hexo/

**Comment by ppoffice** [comment]
@TingSyuanWang @zippoobbiz 
现在使用`hexo generate`可以直接在`public`目录下生成`.nojekyll`文件，但由于`hexo-deploy-git`这个Hexo插件会忽略`.`开头的文件，所以直接使用`hexo deploy`仍然不能将`.nojekyll`文件部署到GitHub上。现在的解决方法是手动部署`public`目录下的文件。我会向Hexo提一个PR，但不能保证一定会Merge。

**Comment by ppoffice** [comment]
已经重命名`vendor`文件夹，不用考虑上述问题了。。。

**Comment by zippoobbiz** [comment]
well done

**Comment by espumitadk** [comment]
Thanks!

**Comment by TingSyuanWang** [comment]
Thanks
