### ISSUE TITLE
如何添加favicon 能详细说一下么

### ISSUE THREAD

**Issue by zippoobbiz** [ppoffice/hexo-theme-hueman#152]
我按照github上面讲解的配置设置
favicon: favicon.png
并把favicon.png放在根目录的source文件夹下，可是依然看不到，我看了index.html里面也没有生成favicon相关代码。我看了别人用hexo-theme-hueman做的网站会有相关的代码生成的，如下
<img width="655" alt="screen shot 2016-11-04 at 10 47 37 am" src="https://cloud.githubusercontent.com/assets/7019612/19989669/35ce7d72-a27c-11e6-8104-ad8c2495c7fb.png">
可是我的并没有，是不是有什么设置不对？或者有什么操作还没做？请指教

**Comment by ppoffice** [comment]
@zippoobbiz 
你还需要生成一个favicon.ico丢到网站的根目录下面才能让浏览器显示Favicon。

**Comment by zippoobbiz** [comment]
我放倒根目录下 但是页面上依然没有饮用favicon.ico的代码 这样也可以么？

**Comment by ppoffice** [comment]
@zippoobbiz 
可以
