### ISSUE TITLE
页面上的subtitle是在哪里添加的？

### ISSUE THREAD

**Issue by zippoobbiz** [ppoffice/hexo-theme-hueman#153]
如题

**Comment by ppoffice** [comment]
@zippoobbiz 
你说的subtitle指的是什么？

**Comment by zippoobbiz** [comment]
http://blog.zhangruipeng.me/hexo-theme-hueman/
上面那句Inspire and empower.

**Comment by zippoobbiz** [comment]
您好？能说一下是怎么添加subtitle的么

**Comment by ppoffice** [comment]
@zippoobbiz 
https://github.com/ppoffice/hexo-theme-hueman/blob/site/_config.yml#L7
