### ISSUE TITLE
scripts下工具函数在哪里被引入

### ISSUE THREAD

**Issue by ManfredHu** [ppoffice/hexo-theme-hueman#159]
额，有个问题问下哈。
```bash
themes/scripts/
```
目录下几个脚本，如
- excerpt.js 
- meta.js
- thumbnail.js
是如何引入的？我看到summary.ejs有用到，可是这几个文件没看到有引入的地方。
我大概知道作用是作为工具函数，但是还是不知道怎么引入，写新主题的时候没引入会报错，烦请告知下哈。

**Comment by ppoffice** [comment]
@ManfredHu 
https://hexo.io/docs/themes.html#scripts
