### ISSUE TITLE
站内搜索及其他一些小问题

### ISSUE THREAD

**Issue by cokePanda** [ppoffice/hexo-theme-hueman#16]
目前配的默认google搜索，用vpn后测试站内搜索，还是跳到google 搜索site：mysite 并没有搜索输入词
这个要怎么设置一下？
sidebar的灰色背景宽度在哪儿定义的？我改动_variables.styl里的sidebar-width只能改动社交图标那一栏
显示archives的时候能不能改成小图标，否则如果文章太多的话，太占空间。
谢谢

**Comment by ppoffice** [comment]
关于搜索：#2

**Comment by cokePanda** [comment]
这个我看过了，但和我的问题不太一样。我是用代理之后测试的，发觉还是没对输入词进行搜索啊，也没有保留在网站页面上，而是跳到google网站上了

**Comment by ppoffice** [comment]
至于sidebar的灰色背景，是由source / css / images / s-left.png 提供的，你可以自己PS一下修改背景图的宽度。
而archives的缩略图的大小可以在/ source / css / _partial / sidebar.styl 里改：
```css
#recent-post 
  li 
    clearfix() 
    padding: 10px 0 10px 94px 
    border-bottom: 1px solid color-border 
    .item-thumbnail 
      opacity: 1 
      margin-left: -94px 
      transition: all 0.2s ease 
      float: left 
      .thumbnail 
        width: 80px /*这里用来改大小*/ 
        height: 80px  /*这里用来改大小*/ 
        display: block 
...
```

**Comment by ppoffice** [comment]
搜索调用的是hexo默认提供的搜索，可能存在一些问题（例如google有可能对搜索查询的query做了改动等等），我建议还是根据自己的需要自定义搜索引擎。

**Comment by cokePanda** [comment]
好的，谢谢
