### ISSUE TITLE
preloader.gif doesn't exist

### ISSUE THREAD

**Issue by jonbgallant** [ppoffice/hexo-theme-hueman#162]
I don't see preloader.gif or preloader@2x.gif in the repo.  Is the intention for people to create their own?

Please make sure these boxes are checked before submitting your issue. Thank you!

- [x ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [ x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

**Comment by ppoffice** [comment]
@jonbgallant 
These are some legacy code I forgot to remove, thank you for pointing out.

**Comment by jonbgallant** [comment]
Thanks.  I'm using it here: http://blog.jongallant.com. Thanks for the effort - It's a great theme.
