### ISSUE TITLE
怎么添加浏览人数/文章浏览量

### ISSUE THREAD

**Issue by hubojing** [ppoffice/hexo-theme-hueman#163]
请问怎么在网站下方显示网站访问人数/浏览人数？以及每篇文章的浏览量？

**Comment by ppoffice** [comment]
你需要使用第三方服务来统计访客数量，可能需要按照相关服务的说明将代码添加到主题`layout`文件夹下面的`footer.ejs`中。

**Comment by hubojing** [comment]
谢谢你，我知道啦。
