### ISSUE TITLE
How to remove sidebar in the article page ?

### ISSUE THREAD

**Issue by sevencai** [ppoffice/hexo-theme-hueman#164]
I find that the sidebar exists in every page, however it does influence  reading  articles.

Is there any ways to remove it or config it to show or disappear?

**Comment by ppoffice** [comment]
@sevencai 
It should work if you remove/comment out these lines:
https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/layout.ejs#L14
https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/style.styl#L74-L79
and set this to `0px`:
https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_variables.styl#L43

**Comment by sevencai** [comment]
After change the responsive.styl and sidebar.ejs, I solved this problem. 

It will be a better theme if users can configure the sidebar in every page .

Thanks a lot!
