### ISSUE TITLE
分享网址的问题

### ISSUE THREAD

**Issue by TingSyuanWang** [ppoffice/hexo-theme-hueman#168]
您好：

[我随边挑一则贴文]
(https://tingsyuanwang.github.io/blogs/2017/03/04/Wordpress-%E8%99%95%E7%90%86%E4%B8%AD%E6%96%87%E6%AA% 94%E5%90%8D%E4%B8%8A%E5%82%B3/)

[分享的网址会变成]
(https://tingsyuanwang.github.io/blogs/blogs/2017/03/04/Wordpress-处理中文档名上传/)

不知道是哪边设定有问题，恳请指教。

**Comment by ppoffice** [comment]
@TingSyuanWang 您看下是不是_config.yml的问题：https://github.com/hexojs/hexo/pull/2056
如果仍然没有解决，请贴一下您的_config.yml的内容和博客中引用这个连接的Markdown。

**Comment by TingSyuanWang** [comment]
@ppoffice 您好

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Vincent's Corner
subtitle: See More! Learn More! Do More!
description: Who knows what fantastic things around Vincent's corner?
author: Vincent Ting Syuan Wang
language: zh-TW
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tingsyuanwang.github.io/blogs
root: /blogs/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
image_dir: images
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: 生活隨筆
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hueman
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
    - markdown-it-abbr
    - markdown-it-emoji

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/TingSyuanWang/blogs
  branch: gh-pages

**Comment by TingSyuanWang** [comment]
@ppoffice 
I think I follow the rule on the document.
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tingsyuanwang.github.io/blogs
```

**Comment by ppoffice** [comment]
或者试下这种，Hexo二级网址确实有点问题
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://ppoffice.github.io
root: /hexo-theme-hueman/

**Comment by TingSyuanWang** [comment]
OMG!

It's worked!

# YOU ARE TERRIFIC!!!
