### ISSUE TITLE
facebook comment setting

### ISSUE THREAD

**Issue by TingSyuanWang** [ppoffice/hexo-theme-hueman#169]
您好：

请问在 Facebook comment 的设定上

是要设定成？
```
comment:
    facebook: true # enter true to enable
```
还是这样呢？
```
comment:
    facebook: # enter true to enable
        language: en_US
        comment_count: 20
        comment_colorscheme: light
```

这两种我都试过，是不是要其他设定呢？

**Comment by ppoffice** [comment]
@TingSyuanWang 主题中没有支持Facebook的这个插件……

**Comment by TingSyuanWang** [comment]
@ppoffice 亲

我是参考PR＃160，看起来已经Merge到Master分支了！

**Comment by ppoffice** [comment]
@TingSyuanWang 
刚刚看到PR #160 的逻辑有点问题，我稍后修复下，十分抱歉。

**Comment by TingSyuanWang** [comment]
# it worked!

should I close this issue?

**Comment by TingSyuanWang** [comment]
![2017-03-07_211850](https://cloud.githubusercontent.com/assets/8935531/23658012/c84a6a34-037b-11e7-8e7c-79af56a810d2.png)

Excuse for I have another problem,
it didn't show the comment's link on the right of the icon.
