### ISSUE TITLE
Removing thumbnails doesn't work

### ISSUE THREAD

**Issue by kp25** [ppoffice/hexo-theme-hueman#17]
It's really a pretty good theme apart from the thumbnails thing. 
Thumbnails: false property doesn't work correctly. Even i set to false images are loading. Being a blog about programming and all, I don't want to any thumbnails on the posts. 
How to disable the thumbnails feature.?

**Comment by ppoffice** [comment]
I made some changes to the layout and style files, you can try to rebuild now.

**Comment by kp25** [comment]
Perfect. Everything works as expected. 
thumbnail: false works.
