### ISSUE TITLE
It does not work with hexo v3.3.5.

### ISSUE THREAD

**Issue by innks** [ppoffice/hexo-theme-hueman#172]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

**Comment by ppoffice** [comment]
@innks What do you mean by `not work`? I tested it locally and it seems fine.

If you mean the share link issue of posts, I think you need to edit `url` in your root `_config.yml` file.

**Comment by innks** [comment]
i am sorry
_config.yml.example <--
