### ISSUE TITLE
Insight Search Tool

### ISSUE THREAD

**Issue by anthonyrussano** [ppoffice/hexo-theme-hueman#173]
Can the insight search be exported as it's own project so that it can be used in other websites or web apps?

**Comment by ppoffice** [comment]
@anthonyrussano It is not an independent library, so I guess you need to migrate it to other projects manually.

**Comment by anthonyrussano** [comment]
is it possible to use this search tool in the default hexo theme?

**Comment by ppoffice** [comment]
@anthonyrussano It's not a standalone plugin, but you can easily migrate it to any other theme if you are familiar with front-end programming.
