### ISSUE TITLE
added extra newline in the lists

### ISSUE THREAD

**Issue by arifpedia** [ppoffice/hexo-theme-hueman#176]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

---
In [hexo-theme-icarus](https://github.com/ppoffice/hexo-theme-icarus) is fine, but in this theme, rendered html will added extra new line in the lists:

Markdown:

```
Fenced code blocks inside lists

1. This is a numbered list.
2. This is a numbered list.
3. I'm going to include a fenced code block as part of this bullet:

    ```
    Code
    More Code
    ```

4. We can put fenced code blocks with syntax highlighting.

    ```c
    printf("Hello, World!");
    ```
```

Screenshot:
![list.png](https://s10.postimg.org/boqt1lvah/list.png)

**Comment by ppoffice** [comment]
@arifpedia This should fix the new line problem. But be aware that if the number of the list item is greater than 9, you will be experiencing missing first digit of list number.

**Comment by arifpedia** [comment]
@ppoffice Thank you :+1:
