### ISSUE TITLE
Incorrect thumbnail image link

### ISSUE THREAD

**Issue by mien** [ppoffice/hexo-theme-hueman#182]
Home page of the web site is referring the correct thumbnail but other pages are not referring to other link. This bug only arise if you pass thumbnail parameter in frontmatter
for example:
correct thumbnail referring on home page of my website : mien.in
incorrect  referencing on page: http://www.mien.in/categories/IOT/ for post on this page i have passed thumbnail parameter in front matter
http://www.mien.in/categories/Machine-Learning/ this page is referring correct thumbnail because I havn't custom thumbail parameter in frontmatter its using hexo default thumbnail

this same issue persist for the recent  post widget

**Comment by ppoffice** [comment]
@mien Please use absolute image URL.

**Comment by mien** [comment]
I am not much into hexo.
using absolute url will make it too tightly coupled,
and how is it working for home page and not other page.

**Comment by ppoffice** [comment]
@mien No, you are not using absolute URL.

This is the path relative to your current URL:
```
images/arduino-esp8266-connection-thumbnail.png
```

This is the absolute path to your root URL:
```
/images/arduino-esp8266-connection-thumbnail.png
```

**Comment by mien** [comment]
awsome thax it worked
