### ISSUE TITLE
about header

### ISSUE THREAD

**Issue by markyong** [ppoffice/hexo-theme-hueman#184]
想在header或者整个背景加个js动画，该怎么修改呢，thanks

**Comment by ppoffice** [comment]
@markyong JavaScript文件都放到这里了：https://github.com/ppoffice/hexo-theme-hueman/tree/master/source/js

然后你可以在这里引用：https://github.com/ppoffice/hexo-theme-hueman/tree/master/source/js

**Comment by markyong** [comment]
今天试了下发现就乱码了，第一次接触这个，基本的原理我还是搞不懂额，比如说各个文件的作用等

**Comment by xiaoxiongzi** [comment]
你好，想在header也就是category的旁边加上文章归档archive，该怎么弄，非常感谢

**Comment by xiaoxiongzi** [comment]
还有看了你的header的technology有二级菜单，这个又是怎么配置的，好喜欢这个主题，只是配置header的时候不是很清楚

**Comment by ppoffice** [comment]
@xiaoxiongzi 请善用wiki与issues搜索

https://github.com/ppoffice/hexo-theme-hueman/issues?utf8=✓&q=二级菜单

**Comment by xiaoxiongzi** [comment]
嗯嗯，解决了，非常感谢
