### ISSUE TITLE
when finish the "Categories inside Main Menu"

### ISSUE THREAD

**Issue by testxin** [ppoffice/hexo-theme-hueman#19]
what's the time.thanks!

**Comment by ppoffice** [comment]
已经在主题中了，请仔细阅读readme

**Comment by HuberyLee** [comment]
我添加了二级分类，但第二次向该分类中添加文章时它会把它当作一个新的分类重新生成，请问这是什么原因？

**Comment by ppoffice** [comment]
@HuberyLee https://github.com/hexojs/hexo/pull/1156
请升级Hexo或者按照链接中的方法修改Hexo源码。
