### ISSUE TITLE
二级菜单

### ISSUE THREAD

**Issue by songyingxin** [ppoffice/hexo-theme-hueman#190]
我在issue中找到关于二级菜单的issue，但是我试过发现会解析错误。
[hueman 是怎么样设置二级菜单？ #61](https://github.com/ppoffice/hexo-theme-hueman/issues/61)
我的配置：
menu:
    Home: /
    About: /about/index.html
    College Life: 
    Technology: /
    - Tools: http://songyingxin.com/categories/tools/
并且我已经在en.yml中标识了Tools，但是会在hexo d -g 时出错。求解答。

**Comment by ppoffice** [comment]
@songyingxin 不支持自定义二级菜单，二级菜单是从博客的分类自动生成的
