### ISSUE TITLE
Math Redering Problems

### ISSUE THREAD

**Issue by ArayCHN** [ppoffice/hexo-theme-hueman#191]
I am not sure whether this is a problem of hexo or hueman. But mathjax rendering is not working properly. Basically I can not write any math in my text without encountering many problems.

For example, the text below is working with mathjax, but is not working when I try it on hexo:

A transformation function $f_{\text{TSM}}$ could be found in the tangent space that maps the initial tangent graph at training to the initial tangent graph at test. That same function $f_{\text{TSM}}$ can be utilized to warp...

Also, double $ is not working properly. You can not include a comma in $$ $$, for example.

I would be posting more of these problems once I encounter them. Thank you!

**Comment by ArayCHN** [comment]
Hope this will help: turns out that you need to use escape sign `\` for any expressions, which makes your code bulky. Even though some maths interpreters boast of the ability to deal with this problem, they don't. You may also check [here](http://aray.pub/2017/10/02/hexo-math/).

**Comment by toaco** [comment]
I also encountered this problem. There are [the preview](https://toaco.github.io/2017/11/08/%E7%BB%9F%E8%AE%A1%E6%9C%BA%E5%99%A8%E7%BF%BB%E8%AF%91%EF%BC%88SMT%EF%BC%89%E7%AE%80%E4%BB%8B/) and [the raw file](https://gist.githubusercontent.com/toaco/6ac364064141a0e7e63fa0a2719610b2/raw/100076f13ed14a624641840d1aacb85ec338b5c1/file.markdown).
