### ISSUE TITLE
Settings for discussions threads

### ISSUE THREAD

**Issue by vajlex** [ppoffice/hexo-theme-hueman#195]
Thanks for developing Hueman!

I have set up the migration from WP to Hexo using Heuman.  Now I am wondering about the settings for Comments section.   

I figured out that Comments can be disabled for particular posts in FrontMatter like
https://hexo.io/docs/front-matter.html#Settings_&_Their_Default_Values

Now,  I would like to allow comments, but **disallow** the upload of photos with comments.  

is there some way to disable all image uploads in _config.yml  ?
   
comment:
    disqus: hexo-theme-hueman # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan:
        appId: # enter the changyan appId here
        appKey: # enter the changyan appKey here
        on: # enter true to enable

Is that possible?   **Thanks very much!**

Couldn't find such info here:
https://github.com/ppoffice/hexo-theme-hueman/wiki/Comment

谢谢！

**Comment by ppoffice** [comment]
@vajlex No, you cannot do that in this theme. You should probably look into the Disqus configuration for help.

**Comment by vajlex** [comment]
Thanks for your reply!  I am checking out Disqus config.

**Comment by vajlex** [comment]
Followup on Disabling Images in Disqus:  I found the setting!
go to https://YOURACCOUNT.disqus.com/admin/settings/community/
UNCHECK  setting "Enable Media Attachments"
