### ISSUE TITLE
Add menu always start with "index."

### ISSUE THREAD

**Issue by bejondshao** [ppoffice/hexo-theme-hueman#198]
Hi

 there,
    I try to add a menu as this in themes/hueman/_config.yml

> menu:
  Home: /
  Categories:
  Tech: http://bejond.org
  About: /about/index.html

but the menu shows "index.tech". The hexo is the latest, 3.4.0. Hueman is the latest too.
Here is the website http://celing.bejond.org
Thank you

**Comment by ppoffice** [comment]
#81 #112

**Comment by bejondshao** [comment]
Thank you for the solution. Sorry for new issue. I'm closing it.
