### ISSUE TITLE
LiveRe评论框加载两次？求解救

### ISSUE THREAD

**Issue by kikitaMoon** [ppoffice/hexo-theme-hueman#199]
你好！非常喜欢您的这个主题，自己一直在用。求助解决粉丝的问题啦~

我自己摸索部署了[Livere（来必力）](https://livere.com/)评论，看起来一切进展顺利，可是最后看页面上会加载两个评论框，请问这是哪里的问题？ 我实现的方法如这个链接中的步骤，请帮忙看看问题在哪，这个问题困扰了好久了。
http://kikitamap.com/2017/12/13/AddLiveRe/

**Comment by git-xuhao** [comment]
@kikitaMoon  你的问题我已经解决了，打开主题下 common 文件夹里面的scripts文件，把第一行删掉，也就是“<%- partial('comment/scripts') %>”这一行删掉，就 ok 了。

**Comment by kikitaMoon** [comment]
@git-xuhao 是的呢，解决了，我已经按照你的方法更新了，感激不尽！
