### ISSUE TITLE
hueman theme search box can't work 

### ISSUE THREAD

**Issue by health365** [ppoffice/hexo-theme-hueman#2]
Hi hueman author, I found the search box do not work. So could you fix the bug or introduce how to configure the search feature?

**Comment by ppoffice** [comment]
working on it

**Comment by ppoffice** [comment]
天朝屏蔽了Google，所以其实你把代理打开的话其实搜索功能是正常的。
你可以尝试更改为其他的搜索引擎：在`\themes\hueman\layout\_partial\header.ejs`中，将
```JavaScript
<%- search_form({text: __('index.search')}) %>
```
替换为
```HTML
<form action="//www.baidu.com/s" method="get" accept-charset="UTF-8" class="search-form">
  <input type="search" name="wd" results="0" class="search-form-input" placeholder="搜索">
  <input type="hidden" name="si" value="你的网址（不带http）">
  <input type="hidden" name="ct" value="你从百度站长工具得到的验证码">
</form>
```
其他的搜索引擎同理了

**Comment by ppoffice** [comment]
@health365 如果没有其它问题，可以关闭这个issue了

**Comment by health365** [comment]
thanks!

**Comment by richlotta** [comment]
Hi Author!
Please let me know the way how to solve the belows when I click Home & About
1.Cannot GET /hexo-theme-hueman/
2.Cannot GET /hexo-theme-hueman/about/index.html
Thanks!

**Comment by ppoffice** [comment]
@richlotta 
1. Please edit url and root settings in site's config file: https://hexo.io/docs/configuration.html#URL
2. Please create a page named "About"
