### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by cokePanda** [ppoffice/hexo-theme-hueman#20]
就是左上角社交工具的图标颜色能改么？
我试图修改sidebar.styl里的social links的li的color值，一直不成功
改a里的hover的before的color值是可以的，但只能鼠标浮上后才有显示
对这些不太熟悉，能解答下么？
谢谢

**Comment by ppoffice** [comment]
改`#sidebar .sidebar-top i `的color就可以

**Comment by cokePanda** [comment]
搞定 多谢
