### ISSUE TITLE
发布到 github 上显示不出来 CSS 样式等，本地预览还是 OK的,这是为什么？

### ISSUE THREAD

**Issue by git-xuhao** [ppoffice/hexo-theme-hueman#200]
期初我以为是我修改的原因，后来我又从新拉了一遍该主题，还是一样的。我没有把网站放在子目录下，切换到其他主题也是正常的，这是为什么呢？请指教！

**Comment by ppoffice** [comment]
@git-xuhao 我这里看起来没问题呀。请你在页面上按下F12查看Console中有无资源加载错误。

**Comment by git-xuhao** [comment]
@ppoffice  现在好了，不知道是什么原因呢，期初以为是缓存，从昨晚上今天中午都是没有 CSS 样式的。然后有切换其他的主题，又切换回来，来回折腾了下，现在好了，但还不知道什么原因。。。。
