### ISSUE TITLE
如何去除文章页面的侧栏？

### ISSUE THREAD

**Issue by HaosUtopia** [ppoffice/hexo-theme-hueman#202]
问题与：https://github.com/ppoffice/hexo-theme-hueman/issues/164 类似
不过用那里提供的方法只能将所有页面的侧栏都去除了，但我想保留主页的，去除文章页面的侧栏应该怎么设置，谢谢！

**Comment by ppoffice** [comment]
@struggle-boy 需要修改layout文件
