### ISSUE TITLE
文章摘要功能

### ISSUE THREAD

**Issue by qymu** [ppoffice/hexo-theme-hueman#205]
请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [x] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [x] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [x] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

你好，我想问下文章摘要功能如何实现，请问可以使用description来显示摘要吗？
像这篇文章里一样: http://blog.csdn.net/heqiangflytosky/article/details/54863185

**Comment by ppoffice** [comment]
@qymu https://github.com/ppoffice/hexo-theme-hueman/issues/154

**Comment by qymu** [comment]
感谢回复，但是 只能实现“前面的内容显示，后面的内容隐藏”的功能，如果是自己另写的摘要，或者想截取中间一段，好像无法实现。这也是我想使用description来显示摘要的原因。

**Comment by ppoffice** [comment]
@qymu 你可以尝试重写https://github.com/ppoffice/hexo-theme-hueman/blob/master/scripts/excerpt.js
