### ISSUE TITLE
Lightgallery caused the website to freeze

### ISSUE THREAD

**Issue by punksinatra** [ppoffice/hexo-theme-hueman#207]
#Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

If I have lightgallery enabled (set to true in config) and I use the image markdown to include 1 or 2 image to a post, it cause the website to freeze/crash when I click on the photo to view it. 

The site will not respond and I have to press escape to go back to the post but no links will be clickable until I refresh the page. 

Happens on both local hexo server or from my webhost

Anyone have ideas?

**Comment by ppoffice** [comment]
@punksinatra Can you show me the location of your website?

**Comment by punksinatra** [comment]
[Here](https://omglulz.wtf/)

[Here is a sample post with light gallery](https://omglulz.wtf/Gallery/)

I also notice even if I disable lightgallery (false in config) the sample gallery page will still show up like lightgallery is enabled will not show all photos like justified gallery should

**Comment by ppoffice** [comment]
@punksinatra Did you put the `https://cdn.jsdelivr.net/lightgallery.js/` in your layout files? This theme already bundles with the lightgallery.js, I think you need to either remove your CDN references or delete the bundled one.

**Comment by punksinatra** [comment]
@ppoffice  nope I did not modify anything from the theme I used it as it is. So should I remove the bundled one?

**Comment by ppoffice** [comment]
@punksinatra Could you please send me your post source markdown file and your theme files so I can see what's wrong?

**Comment by punksinatra** [comment]
@ppoffice 

Hi,

I think I managed to fix the issue not sure what happened but it appears that I had an extra setting for lightgallery in my _config.yml. This was causing the extra cdn links you were seeing from source removing that fix the lightgallery issue. 

Thanks again for your time and wonderful work
