### ISSUE TITLE
Add social_links and no icon shown

### ISSUE THREAD

**Issue by Dedsic** [ppoffice/hexo-theme-hueman#208]
I found there is an [available icon for telegram](https://fontawesome.com/icons/telegram)  
Then I add it in themes/hueman/_config.yml looks like this:
```
social_links: 
        telegram: https://t.me/xxxxx
```
......and no telegram icon shown. Any solution?  
Thanks for your coding and watching.

**Comment by ppoffice** [comment]
@Dedsic You should update the font-awesome files in https://github.com/ppoffice/hexo-theme-hueman/tree/master/source/libs/font-awesome

**Comment by Dedsic** [comment]
@ppoffice Hey I'm back.
I simply add this  
```
.fa-telegram:before {
  content: "\f2c6"; 
}
```
in font-awesome.css , and  
```
fa-telegram:before{content:"\f2c6"}
```  
in font-awesome.min.css. In doing so I got a error icon on the side bar  
<img src="https://vectordigi.tk/images/%E6%88%AA%E5%9B%BE_2018-02-22_23-02-57.png"/>  
I don't know much about fontawesome. Hope you can give me more advice.  
Thank you.

**Comment by ppoffice** [comment]
@Dedsic It does not show because it does not have the icon. You need to download a newer version of font-awesome files and replace the old ones.

**Comment by Dedsic** [comment]
It's done.All icons' working now. Huge Thanks to you!    
For people who have the same problem just in case, like @ppoffice said, download [the newer version](https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.zip) then replace the old one can fix it.
