### ISSUE TITLE
建议增加文章目录功能

### ISSUE THREAD

**Issue by 307590317** [ppoffice/hexo-theme-hueman#211]
建议在文章中增加文章目录功能

**Comment by dc1y** [comment]
支持增加文章目录功能，阅读更方便

**Comment by ppoffice** [comment]
http://blog.zhangruipeng.me/hexo-theme-hueman/2015/03/10/Table-of-Contents-Example/

**Comment by 307590317** [comment]
没有那种类似fix定位的导航么？这样的话每次就不用返回到顶部去找了

**Comment by 307590317** [comment]
或者你可以考虑把它移动到
![image](https://user-images.githubusercontent.com/27839893/37251102-1bbf4550-2544-11e8-9d36-ddab2a55e04a.png)链接的上面

**Comment by dc1y** [comment]
文章目录最好固定在侧边栏……感谢作者，期待中。

**Comment by 307590317** [comment]
期待加入…… 这样的话就不需要每一个段落结束都加一个top了

**Comment by ppoffice** [comment]
现已将目录改为sidebar插件。实现固定定位并不难，难点在于如何权衡它与其它插件的位置。如果使用固定定位的话，如果用户同时希望使用其它插件，必然会对其它插件造成遮盖。对于个人而言，如果确实需要使用固定定位的目录的话，可以自己修改样式表文件并添加JavaScript脚本。

**Comment by dc1y** [comment]
好快，谢谢！
个人觉得进入文章阅读页面后，侧边栏除文章目录外的部件应该可以精简，这样有助于减少干扰让阅读更专注。
而对于首页来说，由于反映的是整个站点的概览，因此侧边栏可以更丰富些。

再次感谢！

**Comment by ArturKlauser** [comment]
The documentation for the catalog widget is missing in https://github.com/ppoffice/hexo-theme-hueman/wiki/Widgets
