### ISSUE TITLE
Valine documentation missing

### ISSUE THREAD

**Issue by noraj** [ppoffice/hexo-theme-hueman#216]
- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

With #186 and #215 I understand that [valine](https://github.com/xCss/Valine) is a comment system. Is that possible to update the documentation accordingly so we can know how to use it https://github.com/ppoffice/hexo-theme-hueman/wiki/Comment

**Comment by Regulust** [comment]
For more information about Valine, please visit [Valine快速开始](https://valine.js.org/quickstart.html).
