### ISSUE TITLE
Bind documentation missing

### ISSUE THREAD

**Issue by noraj** [ppoffice/hexo-theme-hueman#217]
- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

With #185 I understand that there is a bing search support now but tehre is nothing about that in the documentation (https://github.com/ppoffice/hexo-theme-hueman/wiki/Search), is that possible to update it accordingly ?

**Comment by ppoffice** [comment]
@noraj Bing search is not provided by Hueman. Thus, no documentation will be updated.

**Comment by noraj** [comment]
Ok so what does *added bing search verification support* mean?

PS : I'm closing if it is a wontfix.
