### ISSUE TITLE
Post images resize

### ISSUE THREAD

**Issue by RomanBogachev** [ppoffice/hexo-theme-hueman#22]
Greetings! 

Thumbnails of my posts are cropped.
For example 
![](http://habrastorage.org/files/94d/bc7/243/94dbc72430bf4250b7fc8f98f938804d.png)

How can I do to showing full size image in thumbnail? 
Each time it is necessary to adjust the image manually.

P.S. Some problems with GitHub UserContent. Image doesn't show.
https://www.dropbox.com/s/xkczfux2g3wbuhl/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-21%2018.11.05.png?dl=0

**Comment by ppoffice** [comment]
You may want to edit `\themes\hueman\source\css\_partial\article.styl`.
```stylus
...
  .article-summary-inner
    margin-right: 30px
    .thumbnail
      display: block
      width: 100%
      height: 100%
      position: relative
      overflow: hidden
      margin-bottom: 1em
      .thumbnail-image
        display: block
        width: 100%
        height: 100%
        opacity: 1
        background-size: cover // change 'cover' to 'contain'
        // add a new line: background-repeat: no-repeat
        background-position: center
        transition: opacity 0.3s ease-in
...
```
These changes don't apply to the sidebar thumbnails, but you can edit `sidebar.styl` in the same way.

**Comment by RomanBogachev** [comment]
Thank you, @ppoffice!
It's looks like, how i want.

**Comment by RomanBogachev** [comment]
Hello! 

After update there are no functions for this issue.

**Comment by ppoffice** [comment]
What do you mean "no functions"?

**Comment by RomanBogachev** [comment]
Ohh..sorry, i saw clean version and don`t see some code.
Thx
