### ISSUE TITLE
No favicon setting

### ISSUE THREAD

**Issue by vandep** [ppoffice/hexo-theme-hueman#223]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

There is no favicon.ico setting item.Default ico too ugly

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-hueman/blob/master/_config.yml.example#L18
