### ISSUE TITLE
请教一个问题，下拉菜单不出现问题，谢谢！

### ISSUE THREAD

**Issue by xiongzongyang** [ppoffice/hexo-theme-hueman#228]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ √] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [√ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [ √] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [√ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [√ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [√ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

我正常设置了分类以及子分类，在导航栏上也会出现小三角，但是鼠标移进或点击小三角，下来菜单都不会出现，我之前以为是网页加载问题，后来换了很多电脑试，都是这样，遮该如何解决呢，谢谢哈！

**Comment by ppoffice** [comment]
@xiongzongyang 最近将主题的jQuery升级到3.3导致了此问题，我已经将此问题修复，请更新到最新主题代码

**Comment by xiongzongyang** [comment]
非常感谢，问题已经解决了。

**Comment by qzlinqian** [comment]
您好！我也正常设置了分类以及子分类，在导航栏上也会出现小三角，在我本地的macOS上运行hexo server时localhost中的下拉菜单也能够出现，但是deploy到了远程的Ubuntu 16.0之后，下拉菜单就无法出现了，请问这应该如何解决？

**Comment by ppoffice** [comment]
@IrvingBei 请使用开发者工具(F12)检查是否有静态资源没有成功加载

**Comment by qzlinqian** [comment]
> @IrvingBei 请使用开发者工具(F12)检查是否有静态资源没有成功加载

谢谢！我对比了一下，远端好像没有mouseout和mouseover的监听，我确实对这一块不太了解，请问这是什么情况呢？

**Comment by ppoffice** [comment]
@IrvingBei 我这里看你的博客是没有问题的，请尝试使用浏览器的隐身模式（排除缓存的影响）并禁止所有浏览器插件（排除插件的影响）尝试是否问题仍然存在。另外麻烦贴一下F12后console的错误提示（如果有的话）。

**Comment by qzlinqian** [comment]
是缓存的影响，真的太感谢了！（不过最初是因为我更新了主题之后没有hexo clean）
console里的提示是
```
(index):711 GET http://hexo-theme-hueman.disqus.com/count.js
net::ERR_CONNECTION_RESET
```
