### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by mzachh** [ppoffice/hexo-theme-hueman#23]
Hi,

currently search does not work, the query string is not handed over to the search engine.

Can be tested also on demo site: http://ppoffice.github.io/hexo-theme-hueman/

**Comment by ppoffice** [comment]
I think you are in the Google-service-unavailable area if you received a `ERR_CONNECTION_ABORTED` or `ERR_CONNECTION_RESET` error.
You can also implement custom search engine according to #2 .

**Comment by mzachh** [comment]
I think it is an other issue.

Steps to reproduce:

o Search for "test" on http://ppoffice.github.io/hexo-theme-hueman/

o The following resultspage opens:
https://www.google.com/search?q=site:http://ppoffice.github.io/hexo-theme-hueman

Problem: The search term "test" is not included the query paramters of the search url.

Result page should be:
https://www.google.com/search?q=site:http://ppoffice.github.io/hexo-theme-hueman+test

**Comment by ppoffice** [comment]
Which version of hexo do you have?

**Comment by mzachh** [comment]
hueman is latest checkout from master and hexo is 3.0.1

**Comment by ppoffice** [comment]
I think this may help you: https://github.com/hexojs/hexo/pull/1186
