### ISSUE TITLE
[ASK] Using lightgallery CDN

### ISSUE THREAD

**Issue by arifpedia** [ppoffice/hexo-theme-hueman#231]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [x] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [x] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

I plan to use lightgallery CDN rather than local, so i edit file `/layout/plugin/scripts.ejs`:

```ejs
<% if (typeof(isHead) !== 'undefined' && isHead) { %>
    <% if (theme.plugins.lightgallery) { %>
        <%- css('https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css') %>
    <% } %>
    <% if (theme.plugins.justifiedgallery) { %>
        <%- css('https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css') %>
    <% } %>
    <% if (theme.plugins.google_analytics) { %>
        <%- partial('plugin/google-analytics') %>
    <% } %>
    <% if (theme.plugins.baidu_analytics) { %>
        <%- partial('plugin/baidu-analytics') %>
    <% } %>
<% } else if (typeof(isFooter) !== 'undefined' && isFooter) { %>
    <% if (theme.plugins.statcounter && theme.plugins.statcounter.on) { %>
        <%- partial('plugin/statcounter') %>
    <% } %>
<% } else { %>
    <% if (theme.plugins.lightgallery) { %>
        <%- js('https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/js/lightgallery-all.min.js') %>
    <% } %>
    <% if (theme.plugins.justifiedgallery) { %>
        <%- js('https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js') %>
    <% } %>
    <% if (theme.plugins.mathjax) { %>
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
        </script>
        <%- js('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML') %>
    <% } %>
<% } %>
```
But if i clicked on any image in the post, its open link directly (not using lightgallery):
![capture](https://user-images.githubusercontent.com/4081293/44224909-3465b280-a1b6-11e8-992c-798473edc5db.PNG)

**Comment by ppoffice** [comment]
@arifpedia Maybe you are using some new version of the lightGallery, and it isn't compatible with the code. You can check this out:
https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/libs/lightgallery/js/lightgallery.min.js

**Comment by arifpedia** [comment]
Fixed. jQuery must inserted before lightGallery. I recently change head.ejs:

```ejs
...
    <%- js('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js') %>
    <%- partial('plugin/scripts', { isHead: true }) %>
    </head>
...
```
