### ISSUE TITLE
Sidebar Collapse

### ISSUE THREAD

**Issue by leenooks** [ppoffice/hexo-theme-hueman#235]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

This is a great theme for Hexo.

I would like to have the sidebar collapse when Width > 960 (so that the post gets more space) - is that easy to do? Can you provide some tips?

...deon

**Comment by ppoffice** [comment]
@leenooks It should be here https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_responsive.styl#L11

**Comment by leenooks** [comment]
I did see that, thank you - but I dont know how to implement it fo width's greater that 960.

For smaller screens, the side bar automatically collapses and ca be expended "on top" of the main content.

For larger screens (>960), I would like to optionally collapse the left bar, so the main content gets more screen.

Can you provide an example? (I think this would be a nice addition to this template for everybody.)

...deon
