### ISSUE TITLE
Annual Archive

### ISSUE THREAD

**Issue by tex443** [ppoffice/hexo-theme-hueman#240]
Hi,
I am looking for a way to change the archive in the sidebar from monthly to yearly.
So for example:

From:
January 2017 (1)
October 2018 (2)
November 2018 (1)

To:
2017 (1)
2018 (3)

I downloaded hexo-generator-archive and set monthly: false. But I'm not sure if that leads to the goal.
Can someone help me?

Greetings,
  Tex

**Comment by ppoffice** [comment]
@tex443 Edit this: https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/widget/archive.ejs according to this: https://hexo.io/docs/helpers#list-archives

```ejs
<%- list_archives({type: 'yearly'}) %>
```

**Comment by tex443** [comment]
What a shame. That easy.
Works fine. Thanks a lot!
