### ISSUE TITLE
能否增加分列的列数？如何拓宽内页面宽度？

### ISSUE THREAD

**Issue by matrixgardener** [ppoffice/hexo-theme-hueman#242]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki) carefully and created my own configuration file(_config.yml);
- [X] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-hueman/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [X] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [X] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-hueman/wiki)并创建了自己的配置文件(_config.yml)；
- [X] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-hueman/issues)，并且没有找到类似的问题。

解释下：我想将首页的内容列现在有两列增加到三列，以及点进标题后内容页的宽度。

**Comment by ppoffice** [comment]
@matrixgardener 无法增加列数，页面宽度可以在这里修改https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_variables.styl#L47-L53

**Comment by matrixgardener** [comment]
thanks.solved。
