### ISSUE TITLE
并排显示图片

### ISSUE THREAD

**Issue by Captainzj** [ppoffice/hexo-theme-hueman#243]
你好 我想在文章中并排显示图片  我用了以下格式  在本地hexo s中查看正常  部署后无法显示  想请教怎么解决
```
<center class="half">    
    <img src=./Lecture-Neural-Networks-Part-3/opt0.gif width="300"/>
    <img src=./Lecture-Neural-Networks-Part-3/opt.gif width="300"/>
</center>
```

**Comment by ppoffice** [comment]
@Captainzj 可能是图片地址不对，请尝试使用绝对地址。

**Comment by Captainzj** [comment]
部署之后  页面显示
<img width="872" alt="image" src="https://user-images.githubusercontent.com/19644938/48821532-abea4580-ed94-11e8-8a91-1dd42d6022c6.png">

**Comment by ppoffice** [comment]
@Captainzj 你这个绝对路径…………
不是用这个绝对路径，你这个是本地磁盘的绝对路径，不是Web URL的绝对路径。
试试这个: `Captainzj.github.io/Lecture.......`

**Comment by ppoffice** [comment]
#138

**Comment by Captainzj** [comment]
@ppoffice 谢谢！我用了部署后的绝对路径就好了
