### ISSUE TITLE
remove comment icon in Thumbnail image

### ISSUE THREAD

**Issue by qimingyudaowenti** [ppoffice/hexo-theme-hueman#250]
你好，我关闭了所有评论功能，但是Thumbnail展示的图片右上角仍然有这个绿色lvs图标：
![picture](https://user-images.githubusercontent.com/17612199/51667954-11102080-1ffc-11e9-9b7b-164433ad16a8.png)
如何取消这个图标呢？

**Comment by ppoffice** [comment]
@qimingyudaowenti 目前情况下还需要把这一行
https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/comment/counter.ejs#L1
改为
```ejs
<% if (theme.comment && post.comments) { %>
```

**Comment by qimingyudaowenti** [comment]
可能因为我的设置问题，按照你的方式修改并没有成功，不知道为什么`post.comments`的值不是0。但是受到启发，我修改成了这样：
`<% if (theme.comment && 0) { %>`
也达到了效果
感谢帮助！
