### ISSUE TITLE
catalog 功能导致文章标题隐藏了一部分

### ISSUE THREAD

**Issue by ckwen** [ppoffice/hexo-theme-hueman#257]
启用了 catalog 功能后，点击目录里的目录项后，文章的头会被遮盖一部分，无论怎么滚动都出不来，只有刷新才能恢复。

**Comment by ppoffice** [comment]
@ckwen 我这里无法复现，请将问题页面发布出来并提供页面地址

**Comment by ckwen** [comment]
> @ckwen 我这里无法复现，请将问题页面发布出来并提供页面地址
在本地 localhost:4000 访问时会出现，发布到公网通过域名访问没有问题。
