### ISSUE TITLE
icon的问题

### ISSUE THREAD

**Issue by bianfuyuan** [ppoffice/hexo-theme-hueman#26]
主题配置文件里favicon: /favicon.png的设置不起作用。已经将favicon.png放在了hexo/source目录下。是对icon的大小有要求吗，还是通过别的方式设置？多谢作者指教~

**Comment by ppoffice** [comment]
可能是你的绝对路径不对，请帖一下网址或者查看下你的浏览器开发者工具栏中network栏中的favicon获取情况。

**Comment by bianfuyuan** [comment]
嗯，不好意思是我这边的问题。已经解决啦~麻烦您了~
