### ISSUE TITLE
How to make the website the same size as your sample website?

### ISSUE THREAD

**Issue by shj37** [ppoffice/hexo-theme-hueman#267]
The website created locally seems bigger than your sample website (https://blog.zhangruipeng.me/hexo-theme-hueman/) and I prefer yours. Thank you.
![WM2(OP1O{OYR H}BN41{NHR](https://user-images.githubusercontent.com/8279674/69741640-5fd79b00-1176-11ea-927b-127577d97760.png)
![Q)ZDN2RE8Z_P$FQQRR OHTG](https://user-images.githubusercontent.com/8279674/69741713-80075a00-1176-11ea-8916-ada7f1dd37d4.png)

**Comment by ppoffice** [comment]
@shj37 This is caused by the different fonts for Chinese and English characters. (Latin: Titillium Web, Chinese: Microsoft Yahei). You can replace the default fonts with a font that supports both Latin and Asian characters.

https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_variables.styl#L27

**Comment by shj37** [comment]
> @shj37 This is caused by the different fonts for Chinese and English characters. (Latin: Titillium Web, Chinese: Microsoft Yahei). You can replace the default fonts with a font that supports both Latin and Asian characters.
> 
> https://github.com/ppoffice/hexo-theme-hueman/blob/master/source/css/_variables.styl#L27

This is not caused by different languages, not just the font size. I changed back to en, but it still appear to be larger than your sample website. Thank you.

![BRS29F`L_COX19}PPWYF@E](https://user-images.githubusercontent.com/8279674/69781944-9cdd7500-11ea-11ea-9822-a034548d4b51.png)

**Comment by ppoffice** [comment]
@shj37 I tested it on my pc and it is the same to the online one. Could you please deploy your site so I can go check it out?

**Comment by shj37** [comment]
> @shj37 I tested it on my pc and it is the same to the online one. Could you please deploy your site so I can go check it out?

Solved now, the deployed version is the same as yours, thank you
