### ISSUE TITLE
Customize Subtitle

### ISSUE THREAD

**Issue by MRTClubsBlog** [ppoffice/hexo-theme-hueman#273]
Can you please advise how to customize color and size of subtitle text ?
Thank you

**Comment by ppoffice** [comment]
@MRTClubsBlog You can edit subtitle markup here: https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/common/header.ejs#L9-L13

**Comment by MRTClubsBlog** [comment]
Thank you !


www.mrtclubs.com

MRTClubs, une marque de MRTDigital SAS


Le mar. 24 déc. 2019 à 01:31, Ruipeng Zhang <notifications@github.com> a
écrit :
