### ISSUE TITLE
关于insight搜索问题

### ISSUE THREAD

**Issue by Jackie1123** [ppoffice/hexo-theme-hueman#275]
配置insight搜索后浏览器控制台报错。
我已经安装了hexo-generator-json-content
然后在主题配置文件_config.yml中开启insight
但是deploy后发现搜索不可使用，浏览器报错如下
![1qDAyQ.png](https://s2.ax1x.com/2020/02/13/1qDAyQ.png)
一值是insight.js文件中的concat没定义，contect文件也已经生成了
请问如何解决？感谢！

**Comment by ppoffice** [comment]
@Jackie1123 是不是你没有启用生成pages?
https://github.com/alexbruno/hexo-generator-json-content#sections

**Comment by Jackie1123** [comment]
> @Jackie1123 是不是你没有启用生成pages?
> https://github.com/alexbruno/hexo-generator-json-content#sections

感激！成功启用了。希望主题越来越好，加入多一些集成>_<
