### ISSUE TITLE
[bug]: search box font color

### ISSUE THREAD

**Issue by dxh** [ppoffice/hexo-theme-hueman#29]
![qq20150528-2 2x](https://cloud.githubusercontent.com/assets/4088974/7853406/47e7013a-0540-11e5-9064-3cd7c0cec29e.png)

Shown as picture above, text colour in search box is the same as the box background colour, I can see the text when they are selected.

**Comment by ppoffice** [comment]
Which browser are you using? I tested it under latest Firefox, Chrome and IE and none of theme shows a white seachbox.

**Comment by dxh** [comment]
My Platform: safari, Mac OS X.

As your tips, I test it with chrome, the text colour is ok, but bounds of  the search box seem there is a little bug, show as the follow picture
![qq20150528-3 2x](https://cloud.githubusercontent.com/assets/4088974/7853947/05d3aaee-0547-11e5-872c-4b8cb10cfb07.png)
