### ISSUE TITLE
Configure the theme's _config.yml but the logo and sidebar do not work correctly after uploading to github 

### ISSUE THREAD

**Issue by QI-XIANG** [ppoffice/hexo-theme-hueman#295]
### Setting for hueman's _config.yml :
![螢幕擷取畫面 (317)](https://user-images.githubusercontent.com/76467366/138401897-deb8ce27-c4b3-4eac-8f29-31e5998d0550.png)
#### Social link and others work fine, but the logo and sidebar position does not work after editing the _config.yml.
![screencapture-qi-xiang-github-io-2021-10-22-14_02_44](https://user-images.githubusercontent.com/76467366/138402162-53700710-72c5-4fcb-852a-12c4de34e7ab.png)
#### Everything works fine.
![screencapture-localhost-4000-2021-10-22-14_15_16](https://user-images.githubusercontent.com/76467366/138402685-21532a44-8f6c-4938-9609-6e78bda897b2.png)
#### I tried to change my logo file name as logo-header.png, but it does not work though.
![螢幕擷取畫面 (318)](https://user-images.githubusercontent.com/76467366/138402988-3841f958-100d-4ca1-b05d-95f4eb56e367.png)

**Comment by ppoffice** [comment]
@QI-XIANG Please use absolute path for images.

**Comment by QI-XIANG** [comment]
> @QI-XIANG Please use absolute path for images.

Thanks for answering my question. There still remains a little problem that position of the sidebar does not change to right even though I edited the _config.yml.

**Comment by ppoffice** [comment]
@QI-XIANG Clear your browser cache and refresh.

**Comment by QI-XIANG** [comment]
> @QI-XIANG Clear your browser cache and refresh.

I gave it a try, but it didn't work. The sidebar still remains left. I think it may not be a big deal to visit this blog, so I would like to close the discussion later. Thanks a lot for your help.
