### ISSUE TITLE
How to add a thumbnail?

### ISSUE THREAD

**Issue by DongYan28** [ppoffice/hexo-theme-hueman#297]
On home page, I can see my passages with icons like cameras,but I don't know how to change these icons into ones I prefer. Can anyone here help me? I have already tried to add attribute of image into .md file, but it didn's work. Hope for help,thank you!
请问主页文章缩略图怎么修改？全都是显示的相机图标，想改成自己喜欢的。之前试过在md文件里增加image属性，但是没有效果。

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-hueman/wiki/Theme#thumbnail

**Comment by DongYan28** [comment]
Wow,it' so nice of you to reply to me ！Sorry for taking your time because you have mentioned this question in your passage but I ignore it.
Have a nice day！

---Original---
From: "Ruipeng ***@***.***&gt;
Date: Mon, Apr 4, 2022 21:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ppoffice/hexo-theme-hueman] How to add a thumbnail? (Issue #297)




 
https://github.com/ppoffice/hexo-theme-hueman/wiki/Theme#thumbnail
