### ISSUE TITLE
thumbnail are not properly resized

### ISSUE THREAD

**Issue by eephyne** [ppoffice/hexo-theme-hueman#3]
I didn't notice at first (because my test image was almost the same ratio ) but the thumbnails are not resized correctly.

From what I see, you used width and height 100% for the thumb, which is deforming the image if they're not the same ratio.

Is there a way to simply crop and resize ?

If I remove height:100%, the image is cropped at the bottom (put it in the vertical center could be more pretty though) but it will only work for a image where X is greater than Y.

**Comment by ppoffice** [comment]
working on it

**Comment by ppoffice** [comment]
I changed the `img` tag into `span` tag and use css `background` attributes instead of jquery.VMiddleImg.js to control the size of thumbnails. I think this should solve this issue.

**Comment by eephyne** [comment]
seem fine so far :)

I love your reactivity @ppoffice :p
