### ISSUE TITLE
article-excerpt mess code in hueman homepage

### ISSUE THREAD

**Issue by geosmart** [ppoffice/hexo-theme-hueman#32]
I use the hueman theme,but  have a mess code in hueman index.html
article.ejs
``` javascript
  <p class="article-excerpt">
        <% var excerpt;
          if(post.excerpt)
            excerpt = post.excerpt.replace(/\<[^\>]+\>/g, "");
          else{
            excerpt = post.content.replace(/\<[^\>]+\>/g, "").substring(0,200);
          } %>
        <%= excerpt %>
      </p>
```
but the html output is mess code
``` html

#&#x51C6;&#x5907;&#x5185;&#x5BB9; jdk7 X64&#x5B89;&#x88C5;&#x5305;&#xFF08;&#x5B98;&#x7F51;&#x7248;&#x672C;&#xFF1A;jdk-7u80-linux-x64.tar.gz&#xFF09; &#x4E0B;&#x8F7D;&#x540E;&#x5E76;&#x91CD;&#
```
please see the demo in my blog [geosmart.github.io](http://geosmart.github.io/)

any help will appreciate

**Comment by geosmart** [comment]
and my post file encoding is 'utf-8'

**Comment by ppoffice** [comment]
I think it has something to do with your text editor. Which text editor are you using and what's the version of your hexo?

**Comment by ppoffice** [comment]
I noticed that you have right excerpts in the commit you made 2 days ago. And I tested on my computer and found that the new version of Hexo(3.1) is not to blame for the NCR problem of your excerpts. So may I asked which configuration or software did you change in the last 2 days?

**Comment by geosmart** [comment]
$ hexo version
hexo: 3.1.1
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m

**Comment by geosmart** [comment]
and the hexo packge.json
``` json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-deployer-git": "0.0.4",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-feed": "^1.0.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-sitemap": "^1.0.1",
    "hexo-generator-tag": "^0.1.1",
    "hexo-html-minifier": "0.0.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-marked": "^0.2.5",
    "hexo-renderer-stylus": "^0.2.0",
    "hexo-server": "^0.1.2",
    "hexo-toc": "0.0.5"
  }
}
```

**Comment by ppoffice** [comment]
try this out :joy:

**Comment by geosmart** [comment]
Learned the EJS Template  
<%= code %> will parse html 
 <%- code %> will not parse
thanks,now it's ok !
