### ISSUE TITLE
怎么添加favicon？

### ISSUE THREAD

**Issue by PokimLee** [ppoffice/hexo-theme-hueman#34]
favicon.ico需要放着目录哪个位置？
配置文件上如何写？

可以举个例子吗

**Comment by ppoffice** [comment]
放在博客根目录下的source目录下试一试

**Comment by amethystek** [comment]
我试了一下，太大的 icon（128×128）也不会正常显示，改小（16×16）就可以

**Comment by PokimLee** [comment]
@ppoffice 搞定啦，谢谢你
