### ISSUE TITLE
Add feature social_links button Youtube

### ISSUE THREAD

**Issue by jniltinho** [ppoffice/hexo-theme-hueman#36]
Add feature social_links button Youtube

http://fontawesome.io/icon/youtube/

**Comment by ppoffice** [comment]
Now you can add `youtube` along with any other social media network icons according to [FontAwesome](fontawesome.io) in your `_config.yml` file.

**Comment by jniltinho** [comment]
:+1: 
OK, add my Blog -> blog.linuxpro.com.br
