### ISSUE TITLE
Request Feature Implementing Swiftype search

### ISSUE THREAD

**Issue by jniltinho** [ppoffice/hexo-theme-hueman#37]
Request Feature Implementing Swiftype search
https://swiftype.com/

https://swiftype.com/questions/how-can-i-add-a-submit-button-to-my-search-box

**Comment by jniltinho** [comment]
hueman theme very Cool !!!

Thanks !!!

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-hueman#swiftype
