### ISSUE TITLE
footer bug, 

### ISSUE THREAD

**Issue by tim-hub** [ppoffice/hexo-theme-hueman#42]
<% if (theme.sidebar === 'bottom'){ %> <%- partial('_partial/sidebar') %> <% } %>

© <%= date(new Date(), 'YYYY') %> <%= config.author || config.title %> | Contact

footer出现这些，　怎么破？

**Comment by ppoffice** [comment]
你的footer.ejs是不是修改过……

**Comment by tim-hub** [comment]
是的，修改过，

<footer id="footer">
  <% if (theme.sidebar === 'bottom'){ %>
    <%- partial('_partial/sidebar') %>
  <% } %>
  <div class="container">
    <div class="container-inner">
      <a id="back-to-top" href="javascript:;"><i class="icon" id="icon-angle-up"></i></a>
      <div class="credit">
        <h1 class="logo-wrap">
            
        </h1>
		<p>&copy;  <%= date(new Date(), 'YYYY') %> <%= config.author || config.title %> | <a href="/contact" target="_blank">Contact</a></p>



      </div>
    </div>
  </div>
</footer>

**Comment by tim-hub** [comment]
I fix this issue by myself, though I did not know the reason.

The solution is simple, 

just delete footer.ejs~ after you edit footer.ejs
