### ISSUE TITLE
Category drop down list.

### ISSUE THREAD

**Issue by amosbird** [ppoffice/hexo-theme-hueman#44]
How can I make my categories have this drop down list?

![2015-09-21_161040](https://cloud.githubusercontent.com/assets/5085485/9987580/a61c60b0-607b-11e5-9d77-ea9d178e08d1.png)

**Comment by ppoffice** [comment]
https://hexo.io/docs/front-matter.html

Please use subcategory. Example:
```
categories:
- Sports
- Baseball
```
