### ISSUE TITLE
google plus icon does not show up

### ISSUE THREAD

**Issue by amosbird** [ppoffice/hexo-theme-hueman#45]
![2015-09-21_163711](https://cloud.githubusercontent.com/assets/5085485/9988132/7d209e1a-6080-11e5-8505-0f8486f3d464.png)

**Comment by ppoffice** [comment]
https://github.com/ppoffice/hexo-theme-hueman/issues/36

**Comment by amosbird** [comment]
I don't get it. And the link in issue #36 is broken.

**Comment by ppoffice** [comment]
Please use `google-plus`, not `google_plus`

**Comment by amosbird** [comment]
Thanks.
