### ISSUE TITLE
menu 不显示添加的目录

### ISSUE THREAD

**Issue by evindu** [ppoffice/hexo-theme-hueman#48]
![screenpic](http://ww1.sinaimg.cn/large/0060lm7Tgw1ewhz5la6xxj30x10idgqc.jpg)

**Comment by ppoffice** [comment]
example只是示例的配置文件，你需要去掉.example扩展名并放到theme/hueman目录下

**Comment by evindu** [comment]
谢谢解答。 我修改去掉example 之后 发现 archives 和tags 前面会添加index  
![2015-09-28_111830](https://cloud.githubusercontent.com/assets/7939349/10127337/aa01e1e4-65d2-11e5-9781-42229abbd60e.png)

**Comment by ppoffice** [comment]
少了两个翻译，中午补上

**Comment by evindu** [comment]
zh-CN 里面我看有archives 的翻译啊
