### ISSUE TITLE
如何给social_links 添加图标链接？在链接前面加mardown的插入图片语法吗

### ISSUE THREAD

**Issue by evindu** [ppoffice/hexo-theme-hueman#49]
如何给social_links 添加图标链接？在链接前面加mardown的插入图片语法吗？ 
谢谢
![2015-09-28_113159](https://cloud.githubusercontent.com/assets/7939349/10127441/8b58e664-65d4-11e5-8d82-fedfaa175903.png)

**Comment by ppoffice** [comment]
首字母小写

**Comment by evindu** [comment]
知乎 和 豆瓣 无法显示，如何手动添加？

**Comment by ppoffice** [comment]
http://fontawesome.io/icons/ 如果这个里面能搜到的图标都可以添加
