### ISSUE TITLE
Animation of loading image

### ISSUE THREAD

**Issue by RomanBogachev** [ppoffice/hexo-theme-hueman#53]
Hello! 

 At the full article view on the images is animation of loading. But images are already loaded.
 This is only for images after tag 

 How i can fix it? 

![Image example](https://habrastorage.org/files/330/931/182/3309311821464accacf2a24a4ff31b9f.png)

**Comment by ppoffice** [comment]
Do you update the theme to the latest version?

**Comment by RomanBogachev** [comment]
Yes. Last release of theme.

**Comment by ppoffice** [comment]
Which browser are you using? The lazy loading is fine under Chrome 45.
