### ISSUE TITLE
markdown 支持不全

### ISSUE THREAD

**Issue by evindu** [ppoffice/hexo-theme-hueman#54]
**标题的# 号无法支持**  
![tu0](http://i13.tietuku.com/81a3b10375256e16.png)

**还有这个 点 的位置为什么会偏离**

![tu1](http://i13.tietuku.com/df30302dfb85cbf1.png)
![tu2](https://cloud.githubusercontent.com/assets/7939349/10263750/c40eeb10-6a2b-11e5-9d15-c2e0209d5985.png)

**Comment by ppoffice** [comment]
#之后加上空格
至于 7.xxx 你试试把`.`换成`\.`

**Comment by evindu** [comment]
chrome 下 ```- xxxxxx ``` 标点位置是正确的 但是IE  和firefox 下位置不正确 难道和字体有关？

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如
 ```java 
```
显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的

**Comment by rysinal** [comment]
markdown语法为啥不支持
1.自定义编程语言  比如

 ```java 
//这是java语言
Object o = new Object();
```

 ```xml
//这是xml语言
<alpha android:interpolator= “@android:anim/accelerate_decelerate_interpolator”
android:fromAlpha="1.0"
android:toAlpha="0.0"
android:duration="3000" ></alpha> 
```

这种方式在blog里显示的所有语言都是一片黑色的代码块

2.还有> 符号也不支持 显示的是居中效果的 我是根据作业部落的markdown语法写的
