### ISSUE TITLE
compatibility with hexo 3

### ISSUE THREAD

**Issue by eephyne** [ppoffice/hexo-theme-hueman#6]
I would like to know if a compatibility with hexo 3 is planned?
If its not,  I certainly will do it but not as good as you.

**Comment by ppoffice** [comment]
I would like to have a look at the changelog of hexo project and tell the difference between two versions. But hueman will be in long term service and I am grad to provide an update for Hexo 3. It will take some time.

**Comment by eephyne** [comment]
Glad to hear that :)
