### ISSUE TITLE
noindex for tag and categorie pages

### ISSUE THREAD

**Issue by mzachh** [ppoffice/hexo-theme-hueman#68]
Hi,

is it possible to configure that the tags and categories index pages get the noindex tag, e.g.:
<head> <meta name="robots" content="noindex, follow" /> </head>

To remove the pages from Google index. It could be good for SEO to remove the duplicate content issue, also described here: https://moz.com/learn/seo/duplicate-content

**Comment by ppoffice** [comment]
The category system is implemented by Hexo, not its theme. So I think it's better to ask https://github.com/hexojs/hexo/issues :)

**Comment by mzachh** [comment]
I am not sure were to fix this, maybe in both.
AFAIK, the theme writes the `<head>` in https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/_partial/head.ejs

And I would like to add `<meta name="robots" content="noindex, follow" /> ` to `<head>`.

Is there a way to add cleanly customization to the `<head>`?

**Comment by ppoffice** [comment]
Now you can customize meta tags for each post/page through front-matter:

```diff
title: test post
date: 2015-01-26 21:55:37
tags:
comments: false
+ meta:
+ - name="robots";content="noindex, follow"
+ - name="another-meta";value="hello world";enabled=false
```
