### ISSUE TITLE
post size in index depend of text inside the posts

### ISSUE THREAD

**Issue by eephyne** [ppoffice/hexo-theme-hueman#7]
When __all__ the articles have no or very few words, the render of the homepage is not very good,

here an exemple :

![Imgur](http://i.imgur.com/Y5AKU9p.png)

if I fill more words in the article, the render get bigger, if I remove all the words, the render is so small that title get wrapped.

I precise I use hexo 3.0.0-rc4 and I did'nt tested it on hexo 2.8.3

**Comment by ppoffice** [comment]
I made some changes to css files, you can try it out now.

**Comment by eephyne** [comment]
work like a charm (plus the update to 3.0.0  who make everything awesome :) )

a simple question, I did modify some settings in source/css/_variable.styl but of course when a pull need to change the file I need to checkout the file, for now its not annoying since I have only a few changes, but for someone who made big changes inside that could be a pain.
Is it possible to have a _settings.styl in the root who overwrite others styl settings ?
