### ISSUE TITLE
Bad config.yml sample

### ISSUE THREAD

**Issue by EvanCarroll** [ppoffice/hexo-theme-hueman#74]
https://github.com/ppoffice/hexo-theme-hueman/blob/master/_config.yml.example

It doesn't even have the `theme:heuman` in it. Is that correct?

**Comment by ppoffice** [comment]
Is the themes configuration file, not the site's..
https://hexo.io/docs/configuration.html#Site
https://hexo.io/docs/themes.html#config-yml

**Comment by ppoffice** [comment]
I think you can take a look at this: https://github.com/ppoffice/ppoffice.github.io
