### ISSUE TITLE
I see English but Still see Chinese Characters

### ISSUE THREAD

**Issue by dschinkel** [ppoffice/hexo-theme-hueman#76]
How can I rid the Chinese?  I don't want to see both at the same time.  

<img width="1288" alt="screen shot 2015-12-13 at 8 16 00 pm" src="https://cloud.githubusercontent.com/assets/338798/11771470/709b2042-a1d6-11e5-9020-3ad4d095bfff.png">

**Comment by ppoffice** [comment]
Did you set the language to English in your site's config.yml?
```yml
language: en
```

**Comment by dschinkel** [comment]
Yea duh, I just had to rerun the server.  I guess I should have tried that first!

**Comment by ppoffice** [comment]
I took a screenshot in case you edit the wrong config.yml.
![image](https://cloud.githubusercontent.com/assets/8849362/11771638/072e098a-a24e-11e5-8dbe-8a0f55114d47.png)
