### ISSUE TITLE
Maybe a small bug in mobile view

### ISSUE THREAD

**Issue by AndrewXeno** [ppoffice/hexo-theme-hueman#80]
When viewing in low res viewport (i.e. mobile), if users click the Nav menu toggle, they will not be able to fold the menu again, as the toggle is overlapping with the Home menu. I think adding "clear: both" under #main-nav in _responsive.styl will fix the issue.

**Comment by ppoffice** [comment]
Thanks for pointing out :smile:

**Comment by AndrewXeno** [comment]
Great! Love this theme so much!
