### ISSUE TITLE
菜单为什么跟设置的文字不一样呢

### ISSUE THREAD

**Issue by rysinal** [ppoffice/hexo-theme-hueman#82]
![image](https://cloud.githubusercontent.com/assets/9962863/12192822/1ca48388-b61d-11e5-8d6f-53d00167d4a1.png)

多了一个前缀，谢谢解答

**Comment by ppoffice** [comment]
因为菜单调用了翻译：https://github.com/ppoffice/hexo-theme-hueman/blob/master/languages/zh-CN.yml
如果翻译中没有相应值，就会出现这种情况。

**Comment by lamyuqing** [comment]
谢谢解答，那如果我在翻译里添加自己所需的标题，那么怎么像你那个Demo一样
![image](https://cloud.githubusercontent.com/assets/9962863/12193186/be7787b6-b620-11e5-80a5-cc5cfe1e06ba.png) 点击跳转到相应的分类界面呢？还有这个二级菜单怎么添加呢，麻烦了

**Comment by ppoffice** [comment]
如果你只是要分类的话只需要保留`Categories:`这项即可，不需要Design和Android。

关于二级菜单：
https://github.com/ppoffice/hexo-theme-hueman/issues/44

**Comment by shinancao** [comment]
你好，那如果设置Design和Android的话，它们是怎么样出现在这个导航栏上的呢？

**Comment by ppoffice** [comment]
@shinancao 直接在_config.yml加入这两个菜单，然后再翻译文件中的index下面加入菜单的翻译就行了

**Comment by shinancao** [comment]
嗯嗯，谢谢，已弄好了~
