### ISSUE TITLE
sidebar: left # sidebar's position (left or right)

### ISSUE THREAD

**Issue by Talesofwing** [ppoffice/hexo-theme-hueman#83]
I can't set up right in github.io.
but localhost can. why?
when i modified and run hexo g,
the system's said : "INFO  Files loaded in 543 ms
                                INFO  0 files generated in 204 ms"
0 files generated???

**Comment by ppoffice** [comment]
Please remove `.deploy_git` and `public` folders before deployment.

**Comment by Talesofwing** [comment]
ohoh thank you!
