### ISSUE TITLE
評論区

### ISSUE THREAD

**Issue by Talesofwing** [ppoffice/hexo-theme-hueman#85]
We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.

我在hexo上的config 加入了disqus_shortname: kumablog

Your website's shortname is kumablog. 这是我在disqus上的shortname
website url 設置了http://talesofwing.github.io/

為什么還是不行...?

**Comment by ppoffice** [comment]
你注册了Disqus了么？

**Comment by Talesofwing** [comment]
嗯 我注冊了 刚刚解決掉了
那個url打上自己的域名就可以了= =..
之前一直都是用 預設的 /
