### ISSUE TITLE
如何设置文档的预览图片

### ISSUE THREAD

**Issue by ascrutae** [ppoffice/hexo-theme-hueman#88]
您好：

如何设置文档的预览图片，现在打开都默认的是一张图片，如何进行更改？

谢谢

**Comment by ppoffice** [comment]
请在使用前阅读Wiki：
https://github.com/ppoffice/hexo-theme-hueman/wiki/Theme#thumbnail

**Comment by ascrutae** [comment]
谢谢 已经解决
