### ISSUE TITLE
What Sans Font?

### ISSUE THREAD

**Issue by dschinkel** [ppoffice/hexo-theme-hueman#89]
I'm creating some prototypes when redesigning my site with the hueman theme.  I want to know what font I could use in Adobe Photoshop which would be exactly the same font used in this theme.  I haven't been successful getting the font the same in Photoshop yet and really want to get it exact because I do like the font.

**Comment by ppoffice** [comment]
You can use online fonts: https://www.google.com/fonts
You can also upload your web fonts: http://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by dschinkel** [comment]
cool thanks!
