### ISSUE TITLE
How could I change the picture of logo?

### ISSUE THREAD

**Issue by Svtter** [ppoffice/hexo-theme-hueman#9]
Amazing project, it must be the most beautiful theme for hexo.

But I want to change the picture "hueman", is there any way to achieve that?

Thank you.

**Comment by ppoffice** [comment]
Replace `logo-header.png` in `themes\hueman\source\css\images` with your own logo. In the future I will add logo configuration in `_config.yml`.

**Comment by Svtter** [comment]
Get it. Thanks.
