### ISSUE TITLE
I can not install properly 

### ISSUE THREAD

**Issue by 12obin** [ppoffice/hexo-theme-hueman#90]
I am using hexo hueman theme on windows 10, but not working properly
![error-hueman-theme-hexo](https://cloud.githubusercontent.com/assets/6492764/12529538/451a5140-c1ed-11e5-92a7-6a586ef8bd67.PNG)

**Comment by ppoffice** [comment]
Did you rename _config.yml.example?

https://github.com/ppoffice/hexo-theme-hueman/wiki/Installation

**Comment by 12obin** [comment]
I forgot to do that, now working properly. Thanks.

**Comment by 12obin** [comment]
I like this theme, would you like to make hueman theme for gohugo?  :)
