### ISSUE TITLE
new page with recent posts

### ISSUE THREAD

**Issue by ritzton** [ppoffice/hexo-theme-hueman#95]
Hello,

I am using Hexo with Hueman theme and I would like to create a new page with the X last post and without the layout. I would like this page to create an iframe script that can be inserted in another website.
How can I do this ?

Thank you for your help.

**Comment by ppoffice** [comment]
I think this cannot be done without some coding. You can take a look at [recent_posts.ejs](https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/widget/recent_posts.ejs) and create a new layout under the layout folder(take [the index layout](https://github.com/ppoffice/hexo-theme-hueman/blob/master/layout/index.ejs) for example), and then create a new page and [assign its layout to this new layout](https://hexo.io/docs/front-matter.html#Settings__26amp_3B_Their_Default_Values).
