### ISSUE TITLE
Migrate hexo-theme-hueman to Hugo Golang

### ISSUE THREAD

**Issue by jniltinho** [ppoffice/hexo-theme-hueman#98]
I would like to ask a question.
You have time to migrate this theme for Hugo Golang, I can help.

https://gohugo.io/

**Comment by ppoffice** [comment]
Thank you for your proposal, but I'm now working on other projects, so migrating this to other platform is not planned:smiley:

**Comment by jeffreycentex** [comment]
Someone has already done this...
https://github.com/msjulias/blog-au
